kHomePosition = 0
kCruiseVelocity = 0.5
kAcceleration = 4.0
kMaxUnitsLimits = 0.429 + 3m
kMinUnitsLimits = 0.0
kEnableSupplyCurrentLimit = true
kSupplyCurrentLimit = 60.0
kSupplyCurrentThreshold = 80.0
kSupplyCurrentTimeout = 0.5
kMaxForwardOutput = 12.0
kMaxReverseOutput = -12.0