kHomePosition = 0
kMaxUnitsLimit = 0.46
kMinUnitsLimit = 0 
kKp = 1
kKi = 0
kKd = 0
kKa = 0
kKg = 0.2
kDeadband = 0
kCruiseVelocity = 1
kAcceleration = 120
kRampRate = 0
kMaxForwardOutput = 12
kMaxReverseOutput = -12
kEnableSupplyCurrentLimit = true
kSupplyCurrentLimit = 40
kSupplyCurrentThreshold = 40
kSupplyCurrentTimeout = 0.01
kHomingZone = 0.1
kHomingTimeout = 0.5
kHomingVelocity = 0.1
kHomingOutput = -2